# .github/workflows/main.yml

name: Daily News Bot

on:
  schedule:
    # This runs the job every day at 03:30 UTC, which is 9:00 AM IST
    - cron: "30 3 * * *"
  workflow_dispatch: # This allows you to run it manually from the Actions tab

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the Discord bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
        run: python bot.py
